name: calendario_familiar
description: "Calendario familiar compartido con sincronización en tiempo real"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^16.1.0
  flutter_riverpod: ^2.3.6
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  table_calendar: ^3.1.2
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.2.3
  intl: ^0.19.0
  android_alarm_manager_plus: ^5.0.0
  wakelock_plus: ^1.2.8
  audioplayers: ^6.1.0
  # Dependencias faltantes para la app original
  shared_preferences: ^2.2.2
  pdf: ^3.10.7
  printing: ^5.11.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  permission_handler: ^11.2.0
  timezone: ^0.9.2
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_colorpicker: ^1.1.0
  # Dependencias de video eliminadas - splash simplificado
  # Dependencias para notificaciones web
  firebase_messaging: ^15.1.3
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.11
  riverpod_annotation: ^2.3.5
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  # Dependencias para pruebas avanzadas
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  patrol: ^3.19.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/videos/
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
