// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5vvp7IQOZLO7LlsUY_Wq-H8M_5PH3ZQE',
    appId: '1:804273724178:web:c5955a1f657884c0e7f1cb',
    messagingSenderId: '804273724178',
    projectId: 'apptaxi-f2190',
    authDomain: 'apptaxi-f2190.firebaseapp.com',
    storageBucket: 'apptaxi-f2190.firebasestorage.app',
    measurementId: 'G-3D8R30TYTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGE9TrLvHAIwuXn0o6jqFSw5RhS0HDtg8',
    appId: '1:804273724178:android:c5955a1f657884c0e7f1cb',
    messagingSenderId: '804273724178',
    projectId: 'apptaxi-f2190',
    storageBucket: 'apptaxi-f2190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGE9TrLvHAIwuXn0o6jqFSw5RhS0HDtg8',
    appId: '1:804273724178:ios:c5955a1f657884c0e7f1cb',
    messagingSenderId: '804273724178',
    projectId: 'apptaxi-f2190',
    storageBucket: 'apptaxi-f2190.firebasestorage.app',
    iosBundleId: 'com.juancarlos.calendariofamiliar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGE9TrLvHAIwuXn0o6jqFSw5RhS0HDtg8',
    appId: '1:804273724178:ios:c5955a1f657884c0e7f1cb',
    messagingSenderId: '804273724178',
    projectId: 'apptaxi-f2190',
    storageBucket: 'apptaxi-f2190.firebasestorage.app',
    iosBundleId: 'com.juancarlos.calendariofamiliar',
  );
}