name: Deploy PWA to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'  # Compatible con Dart SDK >=3.4.0 y intl ^0.20.2
        channel: 'stable'
        
    - name: Install dependencies
      run: |
        flutter pub get
        # flutter pub upgrade  # Removido para evitar conflictos
      
    - name: Build PWA
      run: flutter build web --release
      
    - name: Create headers file
      run: |
        echo "/*" > build/web/_headers
        echo "  Cross-Origin-Opener-Policy: same-origin-allow-popups" >> build/web/_headers
        echo "  Cross-Origin-Embedder-Policy: unsafe-none" >> build/web/_headers
        echo "  Cross-Origin-Resource-Policy: cross-origin" >> build/web/_headers
        
    - name: Create .htaccess file
      run: |
        echo "Header always set Cross-Origin-Opener-Policy \"same-origin-allow-popups\"" > build/web/.htaccess
        echo "Header always set Cross-Origin-Embedder-Policy \"unsafe-none\"" >> build/web/.htaccess
        echo "Header always set Cross-Origin-Resource-Policy \"cross-origin\"" >> build/web/.htaccess
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        cname: dowhi.github.io
