name: disabled-pages-workflow

on:
  # Desactivado: solo ejecución manual si alguna vez se necesita
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "Workflow desactivado. Usamos GitHub Pages desde main/docs."

